crm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .forms import PasswordResetReCaptchaForm

app_name = 'crm'
urlpatterns = [
    #url(r'^register/$', views.register, name='register'),
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('user_list', views.user_list, name='user_list'),
    path('user/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('user/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('user/<int:pk>/detail/', views.user_detail, name='user_detail'),
    path('boardgames_list', views.boardgames_list, name='boardgames_list'),
    path('boardgames/create/', views.boardgames_new, name='boardgames_new'),
    path('boardgames/<int:pk>/edit/', views.boardgames_edit, name='boardgames_edit'),
    path('boardgames/<int:pk>/delete/', views.boardgames_delete, name='boardgames_delete'),
    path('boardgames/<int:pk>/detail/', views.boardgames_detail, name='boardgames_detail'),
    path('password_reset/', views.PasswordResetReCaptcha.as_view(), name='password_reset'),
    path('user/<int:pk>/trade/', views.all_user_trade_list, name='all_user_trade_list'),
    path('user/<int:pk>/want/', views.all_user_want_list, name='all_user_want_list'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

mfscrm/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

crm/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class CRMUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        CRMUser.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.crmuser.save()


class Boardgames(models.Model):
    # user_name = models.ForeignKey(User, on_delete=models.CASCADE, related_name='boardgames')
    boardgames_title = models.CharField(max_length=100)
    boardgames_genre = models.CharField(max_length=50)
    boardgames_BGG_rank = models.IntegerField()
    boardgames_year = models.IntegerField(default='2021')
    boardgames_player_count_min = models.IntegerField()
    boardgames_player_count_max = models.IntegerField()
    boardgames_msrp = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.id)


class BoardgamesAvailable(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, related_name='gamesAvailable')
    boardgames = models.ForeignKey(Boardgames, on_delete=models.CASCADE)
    boardgames_condition = models.TextField(max_length=50)
    boardgames_notes = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.username)


class BoardgamesRequested(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, related_name='GamesRequested')
    boardgames = models.ForeignKey(Boardgames, on_delete=models.CASCADE)
    boardgames_condition = models.TextField(max_length=50)
    boardgames_notes = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.username)

crm/forms.py
from django import forms
from .models import CRMUser, Boardgames
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CRMUserForm(forms.ModelForm):
    class Meta:
        model = CRMUser
        fields = ('address', 'city', 'state', 'zipcode', 'phone_number')


class BoardGameForm(forms.ModelForm):
    class Meta:
        model = Boardgames
        fields = ('boardgames_title', 'boardgames_genre', 'boardgames_BGG_rank', 'boardgames_year',
                  'boardgames_player_count_min', 'boardgames_player_count_max', 'boardgames_msrp')


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)


class PasswordResetReCaptchaForm(PasswordResetForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

crm/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.db.models import Sum
from _decimal import Decimal
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from .forms import PasswordResetReCaptchaForm

now = timezone.now()


def home(request):
    return render(request, 'crm/home.html',
                  {'crm': home})


@login_required
def user_list(request):
    user = User.objects.filter(is_active=True)
    return render(request, 'crm/user_list.html',
                  {'users': user})


@login_required
def user_edit(request, pk):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = CRMUserForm(request.POST, instance=request.user.crmuser)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
#            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('crm:user_list')
#        else:
#            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = CRMUserForm(instance=request.user.crmuser)
    return render(request, 'crm/user_edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def user_delete(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    return redirect('crm:user_list')


@login_required
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    users = User.objects.filter(username=user.username)
    return render(request, 'crm/user_detail.html', {'users': users})


@login_required
def boardgames_list(request):
    boardgames = Boardgames.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/boardgames_list.html', {'boardgames': boardgames})


@login_required
def boardgames_new(request):
    if request.method == "POST":
        form = BoardGameForm(request.POST)
        if form.is_valid():
            boardgames = form.save(commit=False)
            boardgames.created_date = timezone.now()
            boardgames.save()
            boardgames = Boardgames.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/boardgames_list.html',
                          {'boardgames': boardgames})
    else:
        form = BoardGameForm()
        # print("Else")
    return render(request, 'crm/boardgames_new.html', {'form': form})


@login_required
def boardgames_edit(request, pk):
    boardgames = get_object_or_404(Boardgames, pk=pk)
    if request.method == "POST":
        form = BoardGameForm(request.POST, instance=boardgames)
        if form.is_valid():
            boardgames = form.save()
            # boardgames.user = boardgames.id
            boardgames.updated_date = timezone.now()
            boardgames.save()
            boardgames = Boardgames.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/boardgames_list.html', {'boardgames': boardgames})
    else:
        # print("else")
        form = BoardGameForm(instance=boardgames)
    return render(request, 'crm/boardgames_edit.html', {'form': form})


@login_required
def boardgames_delete(request, pk):
    boardgames = get_object_or_404(Boardgames, pk=pk)
    boardgames.delete()
    return redirect('crm:boardgames_list')


@login_required
def boardgames_detail(request, pk):
    boardgames = get_object_or_404(Boardgames, pk=pk)
    boardgames = Boardgames.objects.filter(boardgames_title=boardgames.boardgames_title)
    return render(request, 'crm/boardgames_detail.html', {'boardgames': boardgames})


@login_required
def all_user_trade_list(request, pk):
    user = get_object_or_404(User, pk=pk)
    users = User.objects.filter(username=user.username)
    return render(request, 'crm/all_user_trade_list.html', {'users': users})


@login_required
def all_user_want_list(request, pk):
    user = get_object_or_404(User, pk=pk)
    users = User.objects.filter(username=user.username)
    return render(request, 'crm/all_user_want_list.html', {'users': users})


@login_required
def add_to_want_list(request, pk):
    model = Boardgames


def register(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return redirect('crm:register')

    else:
        f = CustomUserCreationForm()

    return render(request, 'crm/register.html', {'form': f})


class PasswordResetReCaptcha(PasswordResetView):
    form_class = PasswordResetReCaptchaForm

templates/crm/Enter.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% load static %}
{% block content %}
   <body>
   {% if user.is_authenticated %}
       <div class="page-container">

           <h2 class="top-menu">Welcome to the Omaha area board game swap site!</h2>
           <p>Please choose from below options.</p>
       </div>
   {% endif %}
   <div class="content container">
       <div class="row">
           <div class="col-md-12">
               <div class="links">
                   <!-- Example row of columns -->
                   <div class="row">
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <img src="{% static "images/customer.jpg" %}" alt="User"/>
                               <div class="caption">
                                   <h2>Users</h2>
                                   <p>A list of all users on this site</p>
                                   <p><a class="btn btn-primary" href="{% url 'crm:user_list' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <img src="{% static "images/Games.jpg" %}" alt="games"/>
                               <div class="caption">
                                   <h2>Boardgames</h2>
                                   <p>A list of all board games added to this site</p>
                                   <p><a class="btn btn-primary" href="{% url 'crm:boardgames_list' %}"
                                         role="button">View
                                       details &raquo;</a></p>
                               </div>
                           </div>
                       </div>

                   </div>
               </div>
           </div>
       </div>
   </div>
   </body>

{% endblock %}

</html>

templates/crm/all_user_trade_list.html
{% extends 'crm/base.html' %}
{% block content %}
    {% load mathfilters %}
    {% load humanize %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">All User Trade List</div>
                    <div class="panel-body">
                        Here you can see which users have this board game on their Trade List.
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for boardgames in boardgames %}
            <h1 style="padding-left: 15Px">A List of Users With {{ boardgames.boardgames_title }} in Their Trade
                List</h1>
        {% endfor %}
        <div class="row">
            <h2 style="padding-left: 15Px">User Trade List Information</h2>
        </div>
        <div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="bg-info">
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.user_name }}</td>
                        <td>{{ user.user_first_name }}</td>
                        <td>{{ user.user_last_name }}</td>
                        <td><a href="{% url 'crm:user_detail' pk=user.pk %}"
                               class="btn btn-warning">Go to this Users Page</a>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/crm/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>Omaha Area Board Game Swap Site</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script
            src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Omaha Board Game Swap Site
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'crm:home' %}">Home</a></li>
                <li><a href="{% url 'crm:user_list' %}">Users</a></li>
                <li><a href="{% url 'crm:boardgames_list' %}">Boardgames</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block topcontent %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div {%  if request.path != '/' %} style="display: none;" {% endif %} class="row">
                        <!div class="col-md-3">
                            <h2>Is this what your Board Game Collection looks like?</h2>
                            <div class="thumbnail">
                                <img src="{% static "images/QXTRE6l.jpeg" %}" alt="Games" class="center"/>
                                <div class="caption">
                                    <p>As Board Gamers our collections can exceed our storage capacity.
                                        This site allows a user to list all the games that they are no longer playing
                                        and which are taking up space to be added to their trade list. Other users can then
                                        look through the games and offer trades.</p>
                                    <p><a class="btn btn-default" href="{% url 'login' %}" role="button">LogIn &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/User2.jpg" %}" alt="Users"/>
                                <div class="caption">
                                    <h2>Users</h2>
                                    <p>Sample Text</p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'crm:user_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/Games.jpg" %}" alt="Games"/>
                                <div class="caption">
                                    <h2>Boardgames</h2>
                                    <p>Sample Text</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:boardgames_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/crm/boardgame_detail.html
{% extends 'crm/base.html' %}
{% block content %}
{% load mathfilters %}
{% load humanize %}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Here you can see details for the game and add it to your want list or trade list.
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
  <h1 style="padding-left: 15Px">Board Game Detail for {{ boardgames.boardgames_title }}</h1>


    <div class="row">
        <h2 style="padding-left: 15Px">Board Game Information</h2>
    </div>
    <div class="row">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Title</th>
                <th>Genre</th>
                <th>BGG Rank</th>
                <th>Minimum Players</th>
                <th>Maximum Players</th>
                <th>MSRP</th>

            </tr>
            </thead>
            <tbody>
            {% for boardgames in boardgames %}
                <tr>
                    <td>{{ boardgames.boardgames_title }}</td>
                    <td>{{ boardgames.boardgames_genre }}</td>
                    <td>{{ boardgames.boardgames_BGG_rank }}</td>
                    <td>{{ boardgames.boardgames_player_count_min }}</td>
                    <td>{{ boardgames.boardgames_player_count_max }}</td>
                    <td>{{ boardgames.boardgames_player_count_max }}</td>
                    <td>${{ boardgames.boardgames_msrp }}</td>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/crm/boardgames_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ boardgames_boardgame.title }} for {{ boardgames.user_name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=boardgames.id %} ">Cancel</a>

    </form>

{% endblock %}

</html>

templates/crm/boardgames_detail.html
{% extends 'crm/base.html' %}
{% block content %}
    {% load mathfilters %}
    {% load humanize %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Board Game Detail</div>
                    <div class="panel-body">
                        Here you can see details for a game and add it to your want list or trade list.
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for boardgames in boardgames %}
            <h1 style="padding-left: 15Px">Board Game Detail for {{ boardgames.boardgames_title }}</h1>
        {% endfor %}
        <div class="row">
            <h2 style="padding-left: 15Px">Board Game Information</h2>
        </div>
        <div class="row">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="bg-info">
                    <th>Title</th>
                    <th>Genre</th>
                    <th>BGG Rank</th>
                    <th>Minimum Players</th>
                    <th>Maximum Players</th>
                    <th>MSRP</th>
                </tr>
                </thead>
                <tbody>
                {% for boardgames in boardgames %}
                    <tr>
                    <td>{{ boardgames.boardgames_title }}</td>
                    <td>{{ boardgames.boardgames_genre }}</td>
                    <td>{{ boardgames.boardgames_BGG_rank }}</td>
                    <td>{{ boardgames.boardgames_player_count_min }}</td>
                    <td>{{ boardgames.boardgames_player_count_max }}</td>
                    <td>${{ boardgames.boardgames_msrp }}</td>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <td><a href="{% url 'crm:user_detail' pk=user.pk %}" class="btn btn-warning">Add to my Trade List</a></td>
    <td><a href="{% url 'crm:user_detail' pk=user.pk %}" class="btn btn-warning">Add to my Want List</a></td>
    <td><a href="{% url 'crm:all_user_trade_list' pk=user.pk %}" class="btn btn-warning">All User Trade List</a></td>
    <td><a href="{% url 'crm:all_user_want_list' pk=user.pk %}" class="btn btn-warning">All User Want List</a></td>
{% endblock %}

templates/crm/boardgames_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit Board Game</h1>
    <form method="POST" class="boardgames-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

</html>

templates/crm/boardgames_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Add a New Board Game</h1>
    <form method="POST" class="boardgames-form">{% csrf_token %}
          {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

</html>

templates/crm/register.html
{% extends "crm/base.html" %}

{% block title %}
    Create User - {{ block.super }}
{% endblock %}

{% block content %}

     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>Create account - Board Game Swap</h1>

         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
         </form>
     </div>

{% endblock %}

templates/crm/user_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ user.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=user.user_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

templates/crm/user_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit User</h1>
    <form method="POST">{% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

</html>

templates/crm/user_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'crm/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Omaha Area Board Game Swap Site</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        All Users that have Board Games for trade or that are wanted.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">User Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Username</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                {%  if request.user.is_superuser %}
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>
                <th>Phone Number</th>
                {% endif %}
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    {% if request.user.is_superuser %}
                    <td>{{ user.crmuser.address }}</td>
                    <td>{{ user.crmuser.city }}</td>
                    <td>{{ user.crmuser.state }}</td>
                    <td>{{ user.crmuser.zipcode }}</td>
                    <td>{{ user.crmuser.phone_number }}</td>


                    <td><a href="{% url 'crm:user_edit' pk=user.pk %}"
                           class="btn btn-warning">Edit User</a>

                    <td><a href="{% url 'crm:user_delete' pk=user.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete User</a>
                    {% endif %}
                    <td><a href="{% url 'crm:user_detail' pk=user.pk %}"
                           class="btn btn-primary">User Detail</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}
</html>